### ISSUE TITLE
Suggestion: add a gentle, front-and-center, intro to this project's scope

### ISSUE THREAD

**Issue by sesam** [accordproject/techdocs#108]
To capture first-time visitors, would be benefitted by some infographic or light reading. Maybe most of this project's users are happy with long texts :) as I guess it goes with the domain, I think you could get some Hacktoberfest help from education- and design-skilled people by adding some tasks about generating new explanatory/educational content.

So please see this issue as an encouragement to add some issues :) and I can help generate more ideas on this topic in this thread, or close if you don't need this kind of efforts at this time :). Hope this helps! 

Context:
As a person with interests in { formal languages | crypto-based contracts | helping to bring things mainstream :) }, when taking a first look at Accord, it feels like a complex and compact collection of parts that might even be sub-projects, and to get a hang of what it all contains, a lot of clicking and guessing how things fit together is needed.

**Comment by jeromesimeon** [comment]
@sesam Isn't the main Web site for the Accord Project addressing your request? https://www.accordproject.org

**Comment by irmerk** [comment]
Absolutely I think this helps. We are taking the `v0.20` release as a great opportunity to step back and think about how to structure our documentation in different ways for different audiences, because this isn't really something like `redux`, for example, where everyone using it is likely a developer.

I think #111 is going to be one of the main issue tracking this. I'd absolutely love more input and issues raised by you and others, I think we could certainly use help in this regard.

**Comment by jeromesimeon** [comment]
I would also be interested to know how we could improve the very first page in the documentation:
https://docs.accordproject.org/docs/accordproject.html

**Comment by jeromesimeon** [comment]
@irmerk @peterhunn @4katie I think this issue has been addressed by the latest material / introduction Section? Can we close?
