### ISSUE TITLE
Update Cicero Triangle

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#334]
# Feature Request 🛍️
The [Accord Project triangle](https://docs.accordproject.org/docs/assets/020/template.png), which illustrates Cicero technology, is a bit out of date in regards to [TemplateMark](https://docs.accordproject.org/docs/markup-templatemark.html)

## Possible Solution
1. We need to update the diagram (and everywhere it is shown) to replace CiceroMark with TemplateMark
2. We need another triangle for _documents_ (instances of the template) where CiceroMark will be in the bottom left corner

**Comment by OliverTod** [comment]
Hi team - I have a question about the second diagram that you've mentioned. Apologies in advance if this doesn't make sense.

As I understand it, the suggestion is that we need a second triangle for documents (instances of the template) where CiceroMark will replace TemplateMark in the bottom left corner. However, won't any instance (especially one with CiceroMark) also need TemplateMark grammar in order to parse? If that's the case, shouldn't the diagram be a bit like this:
![image](https://user-images.githubusercontent.com/73812545/102550699-5b2fad00-4112-11eb-8e84-56e0634d7640.png)

If you wanted to make the point even more clear, we could add some diagram along these lines to clarify how a document is created:
![image](https://user-images.githubusercontent.com/73812545/102551153-240dcb80-4113-11eb-8afc-7ca4a465dfcc.png)

**Comment by Arvind644** [comment]
I want to work for this issue. Will you explain me again what to do

**Comment by irmerk** [comment]
@Arvind644 this is a complex issue that will take some research to learn the context around all of AP's technologies. The [link in the original post](https://docs.accordproject.org/docs/markup-templatemark.html) is a good starting point.

**Comment by irmerk** [comment]
@Michael-Grover is there any update on this?

**Comment by jeromesimeon** [comment]
I'm wondering if we need the CiceroMark there. It makes the diagram more complex (and I feel we may need a diagram for contracts -- instead of templates -- down the road anyway, so we may have to change it then again).

So maybe just replacing CiceroMark by TemplateMark is good enough for now?

**Comment by Michael-Grover** [comment]
@jeromesimeon Is this good?
![AP diagram-02](https://user-images.githubusercontent.com/40569793/113046385-03233080-916e-11eb-9343-caebb4ad8545.png)

**Comment by jeromesimeon** [comment]
LGTM @Michael-Grover !
